/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CurrencyCode = { 'ICP' : null } |
  { 'INR' : null } |
  { 'USD' : null };
export interface ExchangeRates {
  'lastUpdated' : bigint,
  'usdToInr' : number,
  'icpToInr' : number,
  'icpToUsd' : number,
}
export interface FuenteIngreso {
  'id' : string,
  'valor' : number,
  'imagenUrl' : [] | [string],
  'descripcion' : string,
  'mesReferencia' : string,
  'fecha' : string,
  'monedaOriginal' : CurrencyCode,
}
export type MesRef = string;
export interface MetaAhorro {
  'id' : string,
  'nombre' : string,
  'ahorroEsteMes' : number,
  'metaTotal' : number,
  'ahorroAcumulado' : number,
}
export interface TotalesMes {
  'gastosTotal' : number,
  'inversionesTotal' : number,
  'saldo' : number,
  'ingresosTotal' : number,
}
export interface Transaccion {
  'id' : string,
  'categoria' : string,
  'metodoPago' : string,
  'valor' : number,
  'imagenUrl' : [] | [string],
  'descripcion' : string,
  'esGastoFijo' : boolean,
  'mesReferencia' : string,
  'esEsencial' : boolean,
  'pagado' : boolean,
  'fecha' : string,
  'monedaOriginal' : CurrencyCode,
}
export interface _SERVICE {
  'addCategoria' : ActorMethod<[string], undefined>,
  'addFuenteIngreso' : ActorMethod<[FuenteIngreso], undefined>,
  'addMetaAhorro' : ActorMethod<[MetaAhorro], undefined>,
  'addMetodoPago' : ActorMethod<[string], undefined>,
  'addTransaccion' : ActorMethod<[Transaccion], undefined>,
  'deleteCategoria' : ActorMethod<[string], undefined>,
  'deleteFuenteIngreso' : ActorMethod<[string], undefined>,
  'deleteMetaAhorro' : ActorMethod<[string], undefined>,
  'deleteMetodoPago' : ActorMethod<[string], undefined>,
  'deleteTransaccion' : ActorMethod<[string], undefined>,
  'getCategorias' : ActorMethod<[], Array<string>>,
  'getExchangeRates' : ActorMethod<[], ExchangeRates>,
  'getFuentesIngreso' : ActorMethod<[MesRef], Array<FuenteIngreso>>,
  'getMesesDisponibles' : ActorMethod<[], Array<MesRef>>,
  'getMetasAhorro' : ActorMethod<[], Array<MetaAhorro>>,
  'getMetodosPago' : ActorMethod<[], Array<string>>,
  'getNotas' : ActorMethod<[MesRef], string>,
  'getTotalesMes' : ActorMethod<[MesRef], TotalesMes>,
  'getTransacciones' : ActorMethod<[MesRef], Array<Transaccion>>,
  'initMes' : ActorMethod<[bigint, bigint], undefined>,
  'setNotas' : ActorMethod<[MesRef, string], undefined>,
  'updateFuenteIngreso' : ActorMethod<[FuenteIngreso], undefined>,
  'updateMetaAhorro' : ActorMethod<[MetaAhorro], undefined>,
  'updateTransaccion' : ActorMethod<[Transaccion], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];