/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CurrencyCode = IDL.Variant({
  'COP' : IDL.Null,
  'ICP' : IDL.Null,
  'USD' : IDL.Null,
});
export const FuenteIngreso = IDL.Record({
  'id' : IDL.Text,
  'valor' : IDL.Float64,
  'imagenUrl' : IDL.Opt(IDL.Text),
  'descripcion' : IDL.Text,
  'mesReferencia' : IDL.Text,
  'fecha' : IDL.Text,
  'monedaOriginal' : CurrencyCode,
});
export const MetaAhorro = IDL.Record({
  'id' : IDL.Text,
  'nombre' : IDL.Text,
  'ahorroEsteMes' : IDL.Float64,
  'metaTotal' : IDL.Float64,
  'ahorroAcumulado' : IDL.Float64,
});
export const Transaccion = IDL.Record({
  'id' : IDL.Text,
  'categoria' : IDL.Text,
  'metodoPago' : IDL.Text,
  'valor' : IDL.Float64,
  'imagenUrl' : IDL.Opt(IDL.Text),
  'descripcion' : IDL.Text,
  'esGastoFijo' : IDL.Bool,
  'mesReferencia' : IDL.Text,
  'esEsencial' : IDL.Bool,
  'pagado' : IDL.Bool,
  'fecha' : IDL.Text,
  'monedaOriginal' : CurrencyCode,
});
export const ExchangeRates = IDL.Record({
  'lastUpdated' : IDL.Int,
  'usdToCop' : IDL.Float64,
  'icpToCop' : IDL.Float64,
  'icpToUsd' : IDL.Float64,
});
export const MesRef = IDL.Text;
export const TotalesMes = IDL.Record({
  'gastosTotal' : IDL.Float64,
  'inversionesTotal' : IDL.Float64,
  'saldo' : IDL.Float64,
  'ingresosTotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addCategoria' : IDL.Func([IDL.Text], [], []),
  'addFuenteIngreso' : IDL.Func([FuenteIngreso], [], []),
  'addMetaAhorro' : IDL.Func([MetaAhorro], [], []),
  'addMetodoPago' : IDL.Func([IDL.Text], [], []),
  'addTransaccion' : IDL.Func([Transaccion], [], []),
  'deleteCategoria' : IDL.Func([IDL.Text], [], []),
  'deleteFuenteIngreso' : IDL.Func([IDL.Text], [], []),
  'deleteMetaAhorro' : IDL.Func([IDL.Text], [], []),
  'deleteMetodoPago' : IDL.Func([IDL.Text], [], []),
  'deleteTransaccion' : IDL.Func([IDL.Text], [], []),
  'getCategorias' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
  'getFuentesIngreso' : IDL.Func([MesRef], [IDL.Vec(FuenteIngreso)], []),
  'getMesesDisponibles' : IDL.Func([], [IDL.Vec(MesRef)], ['query']),
  'getMetasAhorro' : IDL.Func([], [IDL.Vec(MetaAhorro)], ['query']),
  'getMetodosPago' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getNotas' : IDL.Func([MesRef], [IDL.Text], ['query']),
  'getTotalesMes' : IDL.Func([MesRef], [TotalesMes], []),
  'getTransacciones' : IDL.Func([MesRef], [IDL.Vec(Transaccion)], []),
  'initMes' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setNotas' : IDL.Func([MesRef, IDL.Text], [], []),
  'updateFuenteIngreso' : IDL.Func([FuenteIngreso], [], []),
  'updateMetaAhorro' : IDL.Func([MetaAhorro], [], []),
  'updateTransaccion' : IDL.Func([Transaccion], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CurrencyCode = IDL.Variant({
    'COP' : IDL.Null,
    'ICP' : IDL.Null,
    'USD' : IDL.Null,
  });
  const FuenteIngreso = IDL.Record({
    'id' : IDL.Text,
    'valor' : IDL.Float64,
    'imagenUrl' : IDL.Opt(IDL.Text),
    'descripcion' : IDL.Text,
    'mesReferencia' : IDL.Text,
    'fecha' : IDL.Text,
    'monedaOriginal' : CurrencyCode,
  });
  const MetaAhorro = IDL.Record({
    'id' : IDL.Text,
    'nombre' : IDL.Text,
    'ahorroEsteMes' : IDL.Float64,
    'metaTotal' : IDL.Float64,
    'ahorroAcumulado' : IDL.Float64,
  });
  const Transaccion = IDL.Record({
    'id' : IDL.Text,
    'categoria' : IDL.Text,
    'metodoPago' : IDL.Text,
    'valor' : IDL.Float64,
    'imagenUrl' : IDL.Opt(IDL.Text),
    'descripcion' : IDL.Text,
    'esGastoFijo' : IDL.Bool,
    'mesReferencia' : IDL.Text,
    'esEsencial' : IDL.Bool,
    'pagado' : IDL.Bool,
    'fecha' : IDL.Text,
    'monedaOriginal' : CurrencyCode,
  });
  const ExchangeRates = IDL.Record({
    'lastUpdated' : IDL.Int,
    'usdToCop' : IDL.Float64,
    'icpToCop' : IDL.Float64,
    'icpToUsd' : IDL.Float64,
  });
  const MesRef = IDL.Text;
  const TotalesMes = IDL.Record({
    'gastosTotal' : IDL.Float64,
    'inversionesTotal' : IDL.Float64,
    'saldo' : IDL.Float64,
    'ingresosTotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'addCategoria' : IDL.Func([IDL.Text], [], []),
    'addFuenteIngreso' : IDL.Func([FuenteIngreso], [], []),
    'addMetaAhorro' : IDL.Func([MetaAhorro], [], []),
    'addMetodoPago' : IDL.Func([IDL.Text], [], []),
    'addTransaccion' : IDL.Func([Transaccion], [], []),
    'deleteCategoria' : IDL.Func([IDL.Text], [], []),
    'deleteFuenteIngreso' : IDL.Func([IDL.Text], [], []),
    'deleteMetaAhorro' : IDL.Func([IDL.Text], [], []),
    'deleteMetodoPago' : IDL.Func([IDL.Text], [], []),
    'deleteTransaccion' : IDL.Func([IDL.Text], [], []),
    'getCategorias' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
    'getFuentesIngreso' : IDL.Func([MesRef], [IDL.Vec(FuenteIngreso)], []),
    'getMesesDisponibles' : IDL.Func([], [IDL.Vec(MesRef)], ['query']),
    'getMetasAhorro' : IDL.Func([], [IDL.Vec(MetaAhorro)], ['query']),
    'getMetodosPago' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getNotas' : IDL.Func([MesRef], [IDL.Text], ['query']),
    'getTotalesMes' : IDL.Func([MesRef], [TotalesMes], []),
    'getTransacciones' : IDL.Func([MesRef], [IDL.Vec(Transaccion)], []),
    'initMes' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setNotas' : IDL.Func([MesRef, IDL.Text], [], []),
    'updateFuenteIngreso' : IDL.Func([FuenteIngreso], [], []),
    'updateMetaAhorro' : IDL.Func([MetaAhorro], [], []),
    'updateTransaccion' : IDL.Func([Transaccion], [], []),
  });
};

export const init = ({ IDL }) => { return []; };