/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FuenteIngreso {
    id: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    mesReferencia: string;
    fecha: string;
    monedaOriginal: CurrencyCode;
}
export interface Transaccion {
    id: string;
    categoria: string;
    metodoPago: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    esGastoFijo: boolean;
    mesReferencia: string;
    esEsencial: boolean;
    pagado: boolean;
    fecha: string;
    monedaOriginal: CurrencyCode;
}
export type MesRef = string;
export interface TotalesMes {
    gastosTotal: number;
    inversionesTotal: number;
    saldo: number;
    ingresosTotal: number;
}
export interface MetaAhorro {
    id: string;
    nombre: string;
    ahorroEsteMes: number;
    metaTotal: number;
    ahorroAcumulado: number;
}
export interface ExchangeRates {
    lastUpdated: bigint;
    usdToInr: number;
    icpToInr: number;
    icpToUsd: number;
}
export enum CurrencyCode {
    ICP = "ICP",
    INR = "INR",
    USD = "USD"
}
export interface backendInterface {
    addCategoria(nombre: string): Promise<void>;
    addFuenteIngreso(item: FuenteIngreso): Promise<void>;
    addMetaAhorro(item: MetaAhorro): Promise<void>;
    addMetodoPago(nombre: string): Promise<void>;
    addTransaccion(item: Transaccion): Promise<void>;
    deleteCategoria(nombre: string): Promise<void>;
    deleteFuenteIngreso(id: string): Promise<void>;
    deleteMetaAhorro(id: string): Promise<void>;
    deleteMetodoPago(nombre: string): Promise<void>;
    deleteTransaccion(id: string): Promise<void>;
    getCategorias(): Promise<Array<string>>;
    getExchangeRates(): Promise<ExchangeRates>;
    getFuentesIngreso(mesRef: MesRef): Promise<Array<FuenteIngreso>>;
    getMesesDisponibles(): Promise<Array<MesRef>>;
    getMetasAhorro(): Promise<Array<MetaAhorro>>;
    getMetodosPago(): Promise<Array<string>>;
    getNotas(mesRef: MesRef): Promise<string>;
    getTotalesMes(mesRef: MesRef): Promise<TotalesMes>;
    getTransacciones(mesRef: MesRef): Promise<Array<Transaccion>>;
    initMes(anio: bigint, mes: bigint): Promise<void>;
    setNotas(mesRef: MesRef, notas: string): Promise<void>;
    updateFuenteIngreso(item: FuenteIngreso): Promise<void>;
    updateMetaAhorro(item: MetaAhorro): Promise<void>;
    updateTransaccion(item: Transaccion): Promise<void>;
}
import type { CurrencyCode as _CurrencyCode, FuenteIngreso as _FuenteIngreso, Transaccion as _Transaccion } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCategoria(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategoria(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategoria(arg0);
            return result;
        }
    }
    async addFuenteIngreso(arg0: FuenteIngreso): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFuenteIngreso(to_candid_FuenteIngreso_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFuenteIngreso(to_candid_FuenteIngreso_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMetaAhorro(arg0: MetaAhorro): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMetaAhorro(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMetaAhorro(arg0);
            return result;
        }
    }
    async addMetodoPago(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMetodoPago(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMetodoPago(arg0);
            return result;
        }
    }
    async addTransaccion(arg0: Transaccion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaccion(to_candid_Transaccion_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaccion(to_candid_Transaccion_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteCategoria(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategoria(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategoria(arg0);
            return result;
        }
    }
    async deleteFuenteIngreso(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFuenteIngreso(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFuenteIngreso(arg0);
            return result;
        }
    }
    async deleteMetaAhorro(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMetaAhorro(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMetaAhorro(arg0);
            return result;
        }
    }
    async deleteMetodoPago(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMetodoPago(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMetodoPago(arg0);
            return result;
        }
    }
    async deleteTransaccion(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaccion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaccion(arg0);
            return result;
        }
    }
    async getCategorias(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategorias();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategorias();
            return result;
        }
    }
    async getExchangeRates(): Promise<ExchangeRates> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRates();
            return result;
        }
    }
    async getFuentesIngreso(arg0: MesRef): Promise<Array<FuenteIngreso>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFuentesIngreso(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFuentesIngreso(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMesesDisponibles(): Promise<Array<MesRef>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMesesDisponibles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMesesDisponibles();
            return result;
        }
    }
    async getMetasAhorro(): Promise<Array<MetaAhorro>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetasAhorro();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetasAhorro();
            return result;
        }
    }
    async getMetodosPago(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetodosPago();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetodosPago();
            return result;
        }
    }
    async getNotas(arg0: MesRef): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotas(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotas(arg0);
            return result;
        }
    }
    async getTotalesMes(arg0: MesRef): Promise<TotalesMes> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalesMes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalesMes(arg0);
            return result;
        }
    }
    async getTransacciones(arg0: MesRef): Promise<Array<Transaccion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransacciones(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransacciones(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async initMes(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initMes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initMes(arg0, arg1);
            return result;
        }
    }
    async setNotas(arg0: MesRef, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNotas(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNotas(arg0, arg1);
            return result;
        }
    }
    async updateFuenteIngreso(arg0: FuenteIngreso): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFuenteIngreso(to_candid_FuenteIngreso_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFuenteIngreso(to_candid_FuenteIngreso_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMetaAhorro(arg0: MetaAhorro): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMetaAhorro(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMetaAhorro(arg0);
            return result;
        }
    }
    async updateTransaccion(arg0: Transaccion): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaccion(to_candid_Transaccion_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaccion(to_candid_Transaccion_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CurrencyCode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CurrencyCode): CurrencyCode {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_FuenteIngreso_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FuenteIngreso): FuenteIngreso {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Transaccion_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaccion): Transaccion {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoria: string;
    metodoPago: string;
    valor: number;
    imagenUrl: [] | [string];
    descripcion: string;
    esGastoFijo: boolean;
    mesReferencia: string;
    esEsencial: boolean;
    pagado: boolean;
    fecha: string;
    monedaOriginal: _CurrencyCode;
}): {
    id: string;
    categoria: string;
    metodoPago: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    esGastoFijo: boolean;
    mesReferencia: string;
    esEsencial: boolean;
    pagado: boolean;
    fecha: string;
    monedaOriginal: CurrencyCode;
} {
    return {
        id: value.id,
        categoria: value.categoria,
        metodoPago: value.metodoPago,
        valor: value.valor,
        imagenUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.imagenUrl)),
        descripcion: value.descripcion,
        esGastoFijo: value.esGastoFijo,
        mesReferencia: value.mesReferencia,
        esEsencial: value.esEsencial,
        pagado: value.pagado,
        fecha: value.fecha,
        monedaOriginal: from_candid_CurrencyCode_n11(_uploadFile, _downloadFile, value.monedaOriginal)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    valor: number;
    imagenUrl: [] | [string];
    descripcion: string;
    mesReferencia: string;
    fecha: string;
    monedaOriginal: _CurrencyCode;
}): {
    id: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    mesReferencia: string;
    fecha: string;
    monedaOriginal: CurrencyCode;
} {
    return {
        id: value.id,
        valor: value.valor,
        imagenUrl: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.imagenUrl)),
        descripcion: value.descripcion,
        mesReferencia: value.mesReferencia,
        fecha: value.fecha,
        monedaOriginal: from_candid_CurrencyCode_n11(_uploadFile, _downloadFile, value.monedaOriginal)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ICP: null;
} | {
    INR: null;
} | {
    USD: null;
}): CurrencyCode {
    return "ICP" in value ? CurrencyCode.ICP : "INR" in value ? CurrencyCode.INR : "USD" in value ? CurrencyCode.USD : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaccion>): Array<Transaccion> {
    return value.map((x)=>from_candid_Transaccion_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FuenteIngreso>): Array<FuenteIngreso> {
    return value.map((x)=>from_candid_FuenteIngreso_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CurrencyCode_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrencyCode): _CurrencyCode {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FuenteIngreso_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FuenteIngreso): _FuenteIngreso {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Transaccion_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaccion): _Transaccion {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    mesReferencia: string;
    fecha: string;
    monedaOriginal: CurrencyCode;
}): {
    id: string;
    valor: number;
    imagenUrl: [] | [string];
    descripcion: string;
    mesReferencia: string;
    fecha: string;
    monedaOriginal: _CurrencyCode;
} {
    return {
        id: value.id,
        valor: value.valor,
        imagenUrl: value.imagenUrl ? candid_some(value.imagenUrl) : candid_none(),
        descripcion: value.descripcion,
        mesReferencia: value.mesReferencia,
        fecha: value.fecha,
        monedaOriginal: to_candid_CurrencyCode_n3(_uploadFile, _downloadFile, value.monedaOriginal)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoria: string;
    metodoPago: string;
    valor: number;
    imagenUrl?: string;
    descripcion: string;
    esGastoFijo: boolean;
    mesReferencia: string;
    esEsencial: boolean;
    pagado: boolean;
    fecha: string;
    monedaOriginal: CurrencyCode;
}): {
    id: string;
    categoria: string;
    metodoPago: string;
    valor: number;
    imagenUrl: [] | [string];
    descripcion: string;
    esGastoFijo: boolean;
    mesReferencia: string;
    esEsencial: boolean;
    pagado: boolean;
    fecha: string;
    monedaOriginal: _CurrencyCode;
} {
    return {
        id: value.id,
        categoria: value.categoria,
        metodoPago: value.metodoPago,
        valor: value.valor,
        imagenUrl: value.imagenUrl ? candid_some(value.imagenUrl) : candid_none(),
        descripcion: value.descripcion,
        esGastoFijo: value.esGastoFijo,
        mesReferencia: value.mesReferencia,
        esEsencial: value.esEsencial,
        pagado: value.pagado,
        fecha: value.fecha,
        monedaOriginal: to_candid_CurrencyCode_n3(_uploadFile, _downloadFile, value.monedaOriginal)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CurrencyCode): {
    ICP: null;
} | {
    INR: null;
} | {
    USD: null;
} {
    return value == CurrencyCode.ICP ? {
        ICP: null
    } : value == CurrencyCode.INR ? {
        INR: null
    } : value == CurrencyCode.USD ? {
        USD: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
